CurrencyRate.create(rate: 12400.00, finished_at: nil)
Provider.create(name: "Клиент", weight: 1, debt_in_usd: '', debt_in_uzs: '')
Buyer.create(name: "Клиент", weight: 1, debt_in_usd: '', debt_in_uzs: '')
ProductCategory.create(name: 'Склад')
ProductCategory.create(name: 'Сервис', weight: 1)
